import express from "express";
import ProductsController from "./Products.Controller.js";
import FilterController from "./Filters.Controller.js";
import ReviewsController from "./Reviews.Controller.js";
import CustomerController from "./Customer.Controller.js";
const router = express.Router();
router.route('/products/new/:subcategory').post(ProductsController.apiAddProduct);
router.route('/products/:subcategory').get(ProductsController.apiGetAllProducts);
router.route('/products/:subcategory/:productUrl').get(ProductsController.apiGetProductByUrl);
router.route("/items/getcollection").get(ProductsController.apiGetProductsByParams);
router.route('/reviews/:subcategory/:productId').get(ReviewsController.apiGetReviews);
router.route('/filter/:subcategory').get(FilterController.getFilterOptions);
router.route("/customer/login").post(CustomerController.apiCustomerLogin);
router.route("/customer/register").post(CustomerController.apiCustomerRegister);
router.route("/customer/info/:id").get(CustomerController.apiGetCustomerById);
export default router;